### ISSUE TITLE
Add a way of telling plugin to not add content

### ISSUE THREAD

**Issue by mikestreety** [liquidlight/postcss-pseudo-content-insert#1]
In the case where you don't want it to add content, add a flag or custom property to tell plugin not to add it

**Comment by mikestreety** [comment]
Anyone have any ideas how to do this? Is this needed? It needs to not crash gulp-sass...

The only example I can think where you would use if is if you add content in a media query.

```
div:before {
    display: block;
}
@include mq(tablet) {
    div:before {
        content: '';
    }
}
```

Maybe just a simple `content: false;` ?

**Comment by sylvainbaronnet** [comment]
+1
`content: false;` seems fine

**Comment by sylvainbaronnet** [comment]
or maybe content: none; which is valid css

https://developer.mozilla.org/en/docs/Web/CSS/content

**Comment by mikestreety** [comment]
Interesting, i might stick with `false` (and then strip it) as someone might want to genuinely have a `content: none`

**Comment by sylvainbaronnet** [comment]
ok, FYI currently content: none; and content: normal; are replaced by content:'';

**Comment by sylvainbaronnet** [comment]
Sorry it's not the case if i do :

```
:before
  box-sizing inherit
  content none
:after
  box-sizing inherit
  content none
```

But if I do : 

```
:before, :after
  box-sizing inherit
  content normal
```

then content normal is replaced with content ''

**Comment by sylvainbaronnet** [comment]
Maybe it's because #2 fix is not in 0.3.0 ?

**Comment by mikestreety** [comment]
Interesting that normal gets replaced with `''` - maybe thats cssmin doing that?

**Comment by sylvainbaronnet** [comment]
I'm sorry I tried again and it's not the case... 
btw content:normal; seems a good temporary solution until content: false; is implemented

Thank you !
