### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by mikestreety** [liquidlight/postcss-pseudo-content-insert#6]
At the moment, the README is very basic - it should ideally be updated to be a bit more informative.

**Comment by sylvainbaronnet** [comment]
there's `:after,:before{content:''}` added by default, i don't understand why, can you explain ?

**Comment by mikestreety** [comment]
@sylvainbaronnet What version are you on? Mind raising another issue explaining more please :)

**Comment by sylvainbaronnet** [comment]
I use `"postcss-pseudo-content-insert": "^0.3.0"`

ok I'll open an issue

thanks

**Comment by sylvainbaronnet** [comment]
I think I find what happen.

I have this in my css :

```
html
  box-sizing border-box
*, *:before, *:after
  box-sizing inherit
```

so postcss-pseudo-content-insert add this :

```
*:before {
  content: '';
}
*:after {
  content: '';
}
```

And gulp-minify-css change this to : `:after,:before{content:''}`

which make me think, could this be a good idea to just add this line to have content:''; to all :after,:before by default ?

**Comment by mikestreety** [comment]
Ah yeah, this was to do with: https://github.com/liquidlight/postcss-pseudo-content-insert/issues/2

Basically, functionality added in `0.3.0` will just append to the end of your css any rules that don't have a content which were found in a comma seperated list. Rather than appending (https://github.com/liquidlight/postcss-pseudo-content-insert/commit/4d5c211ace0bc80cf4578372c0a0c1586b15cb72) I might just ignore them.
