### ISSUE TITLE
how its different from postcss-pseudo-elements-content?

### ISSUE THREAD

**Issue by iamstarkov** [liquidlight/postcss-pseudo-content-insert#7]
> postcss-pseudo-elements-content adds content: '' to :before-c and :after-c.
> postcss-pseudo-content-insert adds content: '' to :before and :after if it is missing.

I [found these statements](https://github.com/postcss/postcss#others) identical, so can you tell me what is a difference?

**Comment by mikestreety** [comment]
The first one requires a `-c` added to the `:before` (e.g. `div:before-c`) whereas this one does not

**Comment by iamstarkov** [comment]
got it, thank you

**Comment by mikestreety** [comment]
To expand a bit more about where I was coming from with this - I sometimes forget to add the `content: ''` to my pseudo elements, then sometimes spend a few minutes cursing at why they are not working. My slight issue with the `-c` on is that if you can remember to type that, typing `con <tab>` is not much different. 

This one is for those times you _forget_ your content (and also tidy up the CSS a bit more!)

**Comment by iamstarkov** [comment]
I understand you, thanks for the plugin
